name: Static Type Check (MyPy)

on:
  pull_request:
    branches: [ main ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install MyPy
        run: pip install mypy
      - name: Run MyPy
        run: mypy . --ignore-missing-imports
